apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        # env:
        # - name: GF_SESSION_PROVIDER
        #   value: redis
        # - name: GF_SESSION_PROVIDER_CONFIG
        #   value: "addr=redis:6379"
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: so1-p2-201807032
spec:
  type: LoadBalancer
  selector:
    app: grafana
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000