CREATE TABLE HISTORICO_RAM (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    RAM_TOTAL BIGINT,
    RAM_LIBRE BIGINT,
    RAM_UTILIZADA BIGINT,
    PORCENTAJE_UTILIZACION FLOAT,
    FECHA DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE HISTORICO_CPU (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CPU_TOTAL BIGINT,
    PORCENTAJE_UTILIZACION FLOAT,
    FECHA DATETIME DEFAULT CURRENT_TIMESTAMP
);