version: '3'

services:

  mysql:
    image: mysql:latest
    container_name: 'MySQL'
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: so1_proyecto1
    volumes:
      - volume_mysql:/var/lib/mysql
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  backend:
    image: douglassochc/proyecto1_backend:latest
    container_name: 'BackGolang'
    restart: always
    build: ./backend
    environment:
      DB_USER: root
      DB_PASSWORD: root_password
      DB_HOST: mysql
      DB_PORT: 3306
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  frontend:
    image: douglassochc/proyecto1_frontend:latest
    container_name: 'FrontNextJS'
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: /api
    ports:
      - '80:80'
    depends_on:
      - backend

volumes:
  volume_mysql:
    driver: local