apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-consumer
  namespace: so1-p2-201807032
  labels:
    app: consumer-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: consumer-app
  template:
    metadata:
      labels:
        app: consumer-app
    spec:
      containers:
      - name: consumer
        image: douglassochc/proyecto2_consumer:latest
        ports:
        - containerPort: 3000
        env:
        - name: KAFKA_BROKERS
          value: "my-cluster-kafka-bootstrap:9092"
        - name: KAFKA_TOPIC
          value: "topic-so1-p2-201807032"
        - name: REDIS_ADDR
          value: "IP:6379"
        - name: MONGO_HOST
          value: "IP:27017"
        - name: MONGO_USER
          value: "admin"
        - name: MONGO_PASSWORD
          value: "password"
        - name: MONGO_DB_NAME
          value: "proyecto2"
        - name: MONGO_COLLECTION_NAME
          value: "coleccion"
---
apiVersion: v1
kind: Service
metadata:
  name: service-consumer-app
  namespace: so1-p2-201807032
spec:
  type: NodePort
  selector:
    app: consumer-app
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000