version: '3'

services:

  consumer:
    image: douglassochc/proyecto2_consumer:v1
    container_name: 'Deployment'
    restart: always
    build: ./
    environment:
      KAFKA_BROKERS: "my-cluster-kafka-bootstrap:9092"
      KAFKA_TOPIC: "topic-so1-p2-201807032"
    ports:
      - "3000:3000"