apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: deployment-consumer-hpa
  namespace: so1-p2-201807032
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-consumer
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 25