version: '3'

services:

  servidor:
    image: douglassochc/proyecto2_grpc_servidor:v1
    container_name: 'GRPCServer'
    restart: always
    build: ./servidor
    environment:
      KAFKA_BROKERS: "my-cluster-kafka-bootstrap:9092"
      KAFKA_TOPIC: "topic-so1-p2-201807032"
      SERVER_PORT: 3001
    ports:
      - "3001:3001"

  cliente:
    image: douglassochc/proyecto2_grpc_cliente:v1
    container_name: 'GRPCClient'
    restart: always
    build: ./cliente
    environment:
      SERVER_HOST: "localhost:3001"
    ports:
      - "3000:3000"
    depends_on:
      - servidor