version: '3'

services:

  servidor:
    image: douglassochc/proyecto2_grpc_servidor:latest
    container_name: 'GRPCServer'
    restart: always
    build: ./sevidor
    environment:
      DB_HOST: localhost
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: proyecto2
      SERVER_PORT: 3001
    ports:
      - "3001:3001"

  cliente:
    image: douglassochc/proyecto2_grpc_cliente:latest
    container_name: 'GRPCClient'
    restart: always
    build: ./cliente
    ports:
      - "3000:3000"
    depends_on:
      - servidor