version: '3'

services:

  mongo:
    image: go
    container_name: 'MongoDB'
    restart: always
    volumes:
      - volume_mongo:/var/lib/mongo
    ports:
      - "27017:27017"

  backend:
    image: "tarea2_backend"
    container_name: 'BackNodeJS'
    restart: always
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  frontend:
    image: 'tarea2_frontend'
    container_name: 'FrontReactJS'
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  volume_mongo:
    driver: local