apiVersion: apps/v1
kind: Deployment
metadata:
  name: producers-grpc
  namespace: so1-p2-201807032
  labels:
    app: grpc-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-app
  template:
    metadata:
      labels:
        app: grpc-app
    spec:
      containers:
      - name: grpc-server
        image: douglassochc/proyecto2_grpc_servidor:v1
        ports:
        - containerPort: 3001
        env:
        - name: KAFKA_BROKERS
          value: "my-cluster-kafka-bootstrap:9092"
        - name: KAFKA_TOPIC
          value: "topic-so1-p2-201807032"
        - name: SERVER_PORT
          value: "3001"

      - name: grpc-client
        image: douglassochc/proyecto2_grpc_cliente:v1
        ports:
        - containerPort: 3000
        env:
        - name: SERVER_HOST
          value: "localhost:3001"
---
apiVersion: v1
kind: Service
metadata:
  name: service-grpc-app
  namespace: so1-p2-201807032
spec:
  type: ClusterIP
  selector:
    app: grpc-app
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000